[package]
name = "yoink"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2"
colored = "2.1"
indicatif = "0.17"
walkdir = "2.5"
glob = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = 'abort'
